export const queryKeys = {
  opportunities: ["opportunities"] as const,
  opportunitiesByKind: (kind: string) => ["opportunities", kind] as const,
  opportunity: (id: string) => ["opportunities", id] as const,
  carriers: ["carriers"] as const,
  carrier: (id: string) => ["carriers", id] as const,
  snapshots: (carrierId: string) => ["snapshots", carrierId] as const,
  activities: (leadId: string) => ["activities", leadId] as const,
  calls: ["calls"] as const,
  call: (id: string) => ["calls", id] as const,
  cases: ["cases"] as const,
  case: (id: string) => ["cases", id] as const,
  documents: (caseId: string) => ["documents", caseId] as const,
  tasks: (caseId: string) => ["tasks", caseId] as const,
  regulations: ["regulations"] as const,
  regulation: (id: string) => ["regulations", id] as const,
  matches: (regulationId: string) => ["matches", regulationId] as const,
  allMatches: ["matches"] as const,
  attention: ["attention"] as const,
};
